import type { ScenarioCreateInput } from "../models/Scenario.js";

export const PRESET_SCENARIOS: ScenarioCreateInput[] = [
  {
    title: "Restaurant",
    category: "Travel",
    difficulty: "Beginner",
    icon: "🍽",
    description: "Order food, ask for recommendations, and pay the bill.",
    learningGoal: "Order confidently and politely",
    grammarFocus: ["polite requests", "want/like verbs"],
    vocabularyTags: ["food", "payment", "menu"],
    conversationFlow: ["Arrival", "Ordering", "Special requests", "Paying", "Goodbye"],
    estimatedMinutes: 12,
    promptTemplate:
      "You are a friendly restaurant server. Help the learner practice ordering food, asking about the menu, and paying.",
  },
  {
    title: "Airport Check-In",
    category: "Travel",
    difficulty: "Beginner",
    icon: "✈",
    description: "Check in for a flight and answer common airport questions.",
    learningGoal: "Handle airport check-in calmly",
    grammarFocus: ["questions", "future plans"],
    vocabularyTags: ["travel", "documents", "luggage"],
    conversationFlow: ["Greeting", "Documents", "Luggage", "Gate info", "Goodbye"],
    estimatedMinutes: 10,
    promptTemplate:
      "You are an airport check-in agent. Guide the learner through passport checks, luggage, and gate information.",
  },
  {
    title: "Hotel Check-In",
    category: "Travel",
    difficulty: "Beginner",
    icon: "🏨",
    description: "Check into a hotel and ask about amenities.",
    learningGoal: "Complete a hotel check-in",
    grammarFocus: ["polite questions", "possession"],
    vocabularyTags: ["hotel", "rooms", "amenities"],
    conversationFlow: ["Greeting", "Booking name", "Room details", "Amenities", "Key handover"],
    estimatedMinutes: 10,
    promptTemplate:
      "You are a hotel receptionist. Help the learner check in, confirm their reservation, and answer amenity questions.",
  },
  {
    title: "Coffee Shop",
    category: "Daily Life",
    difficulty: "Beginner",
    icon: "☕",
    description: "Order drinks and make small talk with a barista.",
    learningGoal: "Order drinks naturally",
    grammarFocus: ["would like", "sizes"],
    vocabularyTags: ["coffee", "pastries", "small talk"],
    conversationFlow: ["Greeting", "Order", "Customization", "Pickup", "Small talk"],
    estimatedMinutes: 8,
    promptTemplate:
      "You are a cheerful barista. Take the learner's coffee order and keep light conversation going.",
  },
  {
    title: "Shopping",
    category: "Daily Life",
    difficulty: "Beginner",
    icon: "🛒",
    description: "Ask about sizes, prices, and try on clothes.",
    learningGoal: "Shop and negotiate politely",
    grammarFocus: ["comparisons", "prices"],
    vocabularyTags: ["clothes", "sizes", "money"],
    conversationFlow: ["Greeting", "Looking for item", "Size/color", "Price", "Checkout"],
    estimatedMinutes: 10,
    promptTemplate:
      "You are a helpful shop assistant. Help the learner find items, discuss sizes/prices, and complete a purchase.",
  },
  {
    title: "Doctor Visit",
    category: "Health",
    difficulty: "Intermediate",
    icon: "🏥",
    description: "Describe symptoms and understand simple medical advice.",
    learningGoal: "Explain health problems clearly",
    grammarFocus: ["present perfect", "body vocabulary"],
    vocabularyTags: ["symptoms", "medicine", "appointments"],
    conversationFlow: ["Greeting", "Symptoms", "Questions", "Advice", "Follow-up"],
    estimatedMinutes: 12,
    promptTemplate:
      "You are a kind doctor. Ask about symptoms, clarify details, and give simple advice. Keep the tone reassuring.",
  },
  {
    title: "Job Interview",
    category: "Business",
    difficulty: "Intermediate",
    icon: "💼",
    description: "Answer common interview questions professionally.",
    learningGoal: "Speak about experience and strengths",
    grammarFocus: ["past tense", "formal register"],
    vocabularyTags: ["work", "skills", "experience"],
    conversationFlow: ["Introductions", "Experience", "Strengths", "Scenario question", "Closing"],
    estimatedMinutes: 15,
    promptTemplate:
      "You are a professional hiring manager conducting a job interview. Ask realistic questions and keep a formal tone.",
  },
  {
    title: "Business Meeting",
    category: "Business",
    difficulty: "Advanced",
    icon: "📊",
    description: "Discuss project updates and negotiate next steps.",
    learningGoal: "Participate in workplace meetings",
    grammarFocus: ["conditionals", "suggestions"],
    vocabularyTags: ["projects", "deadlines", "negotiation"],
    conversationFlow: ["Agenda", "Updates", "Problems", "Proposals", "Next steps"],
    estimatedMinutes: 15,
    promptTemplate:
      "You are a colleague running a business meeting. Discuss deadlines, blockers, and next actions professionally.",
  },
  {
    title: "Friends Catch-Up",
    category: "Social",
    difficulty: "Beginner",
    icon: "🎉",
    description: "Casual conversation about weekend plans and hobbies.",
    learningGoal: "Make friendly small talk",
    grammarFocus: ["present continuous", "invitations"],
    vocabularyTags: ["hobbies", "plans", "feelings"],
    conversationFlow: ["Greeting", "Recent news", "Plans", "Invitation", "Goodbye"],
    estimatedMinutes: 8,
    promptTemplate:
      "You are a close friend meeting for a casual catch-up. Be warm, curious, and conversational.",
  },
  {
    title: "Public Transport",
    category: "Travel",
    difficulty: "Beginner",
    icon: "🚌",
    description: "Ask for directions and buy tickets.",
    learningGoal: "Navigate transit independently",
    grammarFocus: ["directions", "imperatives"],
    vocabularyTags: ["buses", "tickets", "directions"],
    conversationFlow: ["Ask for help", "Route info", "Ticket", "Confirmation", "Thanks"],
    estimatedMinutes: 8,
    promptTemplate:
      "You are a transit information clerk. Help the learner find the right route and buy a ticket.",
  },
  {
    title: "Bank Visit",
    category: "Daily Life",
    difficulty: "Intermediate",
    icon: "🏦",
    description: "Open an account or ask about a transfer.",
    learningGoal: "Handle basic banking conversations",
    grammarFocus: ["formal requests", "numbers"],
    vocabularyTags: ["money", "accounts", "transfers"],
    conversationFlow: ["Greeting", "Request", "Details", "Confirmation", "Closing"],
    estimatedMinutes: 12,
    promptTemplate:
      "You are a bank teller. Help the learner with an account question or money transfer carefully and clearly.",
  },
  {
    title: "Customer Support Call",
    category: "Business",
    difficulty: "Intermediate",
    icon: "☎",
    description: "Explain a problem and request a solution over the phone.",
    learningGoal: "Resolve issues politely by phone",
    grammarFocus: ["problem description", "polite insistence"],
    vocabularyTags: ["orders", "refunds", "technical issues"],
    conversationFlow: ["Greeting", "Problem", "Clarifying questions", "Solution", "Closing"],
    estimatedMinutes: 12,
    promptTemplate:
      "You are a customer support agent on a phone call. Diagnose the learner's issue and offer a clear solution.",
  },
];
